# Site settings
title: Josh Teague · Product Design · Atlanta, GA USA
email: joshteague@gmail.com
description: Josh Teague is an Atlanta-based product designer currently making FulLStory, previously Google.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joshteague.com"
twitter_username: joshteague

# Build settings
markdown: kramdown
