# Site settings
name: Josh Teague
title: Josh Teague • Digital Product Design and Strategy
email: joshteague@gmail.com
description: "Josh is a digital product designer in Atlanta, GA, USA."
baseurl: ""
url: "http://joshteague.com"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title.html

sass:
  style: :compressed
